# Generated by Django 2.1.5 on 2021-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210222_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mob',
            field=models.CharField(max_length=10),
        ),
    ]
